import { BiMenu, BiSolidShoppingBags } from "react-icons/bi";
import { BsSmartwatch, BsPhone } from "react-icons/bs";
import { FaTshirt } from "react-icons/fa";
import { FaComputer } from "react-icons/fa6";
import { AiOutlineClose } from "react-icons/ai";
import { PiTelevisionFill } from "react-icons/pi";
import { MdOutlineWatch } from "react-icons/md";
import { IoBedOutline } from "react-icons/io5";
import { GoKebabHorizontal } from "react-icons/go";
const categories = [
  {
    id: 1,
    name: "Fashion",
    slug: "fashion",
    description:
      "Explore the latest trends in clothing, footwear, and accessories. Find stylish options in categories like Clothing and Footwear.",
    icon: FaTshirt,
    image: "",
  },
  {
    id: 2,
    name: "Electronics",
    slug: "electronics",
    description:
      "Discover cutting-edge electronics, including Smartphones, Tablets, and Computers. Stay up-to-date with the latest technology trends.",
    icon: PiTelevisionFill,
    image: "",
  },
  {
    id: 3,
    name: "Phones",
    slug: "phones",
    description:
      "Stay connected with the best mobile phones. Explore our collection of Phones and Tablets for the latest models.",
    icon: BsPhone,
    image: "",
  },
  {
    id: 4,
    name: "Computers",
    slug: "computers",
    description:
      "Enhance your productivity with powerful laptops and desktops. Shop in the Computers category for top computing solutions.",
    icon: FaComputer,
    image: "",
  },
  {
    id: 5,
    name: "Watches",
    slug: "watches",
    description:
      "Stay punctual and fashionable with our premium Watch collection. Choose from a variety of stylish timepieces.",
    icon: BsSmartwatch,
    image: "",
  },
  {
    id: 6,
    name: "Digital Watches",
    slug: "digital-watches",
    description:
      "Experience the future of timekeeping with Digital Watches. Discover our range of smart timepieces.",
    icon: MdOutlineWatch,
    image: "",
  },
  {
    id: 7,
    name: "Beddings",
    slug: "beddings",
    description:
      "Rest in comfort with our high-quality Beddings. Explore options like Bedsheets and Pillows for a good night's sleep.",
    icon: IoBedOutline,
    image: "",
  },
  {
    id: 8,
    name: "Bags",
    slug: "bags",
    description:
      "Carry your essentials in style with our Bags collection. Find a variety of fashionable bags for every occasion.",
    icon: BiSolidShoppingBags,
    image: "",
  },
];

const subCategories = [
  //Fashion
  { id: 1, catId: 1, title: "Shoes" },
  { id: 2, catId: 1, title: "Pants" },
  { id: 3, catId: 1, title: "Shirts" },
  { id: 4, catId: 1, title: "T-Shirts" },
  { id: 5, catId: 1, title: "Accessories" },
  { id: 6, catId: 1, title: "Sweaters" },
  { id: 7, catId: 1, title: "Suits" },
  //Electronics
  { id: 8, catId: 2, title: "Fridges" },
  { id: 9, catId: 2, title: "TVs" },
  { id: 10, catId: 2, title: "Woofers" },
];
const products = [
  //SHOES
  {
    id: 1,
    title: "Suede Shoes",
    image: "/shoes/suede/4.jpg",
    slug: "suede-shoes",
    subCatId: 1,
    catId: 1,
    description: "Classic suede shoes for a sophisticated look.",
    hasFreeDelivery: true,
    currentPrice: 69.99,
    originalPrice: 79.99,
    subCatName: "Shoes",
    images: [
      "/shoes/suede/1.jpg",
      "/shoes/suede/2.jpg",
      "/shoes/suede/3.jpg",
      "/shoes/suede/4.jpg",
      "/shoes/suede/5.jpg",
      "/shoes/suede/6.jpg",
      "/shoes/suede/7.jpg",
      "/shoes/suede/8.jpg",
      "/shoes/suede/9.jpg",
      "/shoes/suede/10.jpg",
      "/shoes/suede/12.jpg",
      "/shoes/suede/13.jpg",
      "/shoes/suede/14.jpg",
      "/shoes/suede/15.jpg",
      "/shoes/suede/16.jpg",
      "/shoes/suede/17.jpg",
      "/shoes/suede/18.jpg",
      "/shoes/suede/19.jpg",
      "/shoes/suede/21.jpg",
    ],
  },
  {
    id: 2,
    title: "Mocasin",
    image: "/shoes/mocasin/19.jpg",
    slug: "mocasin",
    subCatId: 1,
    catId: 1,
    description: "Comfortable mocasin shoes for a casual style.",
    hasFreeDelivery: true,
    currentPrice: 49.99,
    originalPrice: 59.99,
    subCatName: "Shoes",
    images: [
      "/shoes/mocasin/1.jpg",
      "/shoes/mocasin/2.jpg",
      "/shoes/mocasin/3.jpg",
      "/shoes/mocasin/4.jpg",
      "/shoes/mocasin/5.jpg",
      "/shoes/mocasin/6.jpg",
      "/shoes/mocasin/7.jpg",
      "/shoes/mocasin/8.jpg",
      "/shoes/mocasin/9.jpg",
      "/shoes/mocasin/10.jpg",
      "/shoes/mocasin/12.jpg",
      "/shoes/mocasin/13.jpg",
      "/shoes/mocasin/14.jpg",
      "/shoes/mocasin/15.jpg",
      "/shoes/mocasin/16.jpg",
      "/shoes/mocasin/17.jpg",
      "/shoes/mocasin/18.jpg",
      "/shoes/mocasin/19.jpg",
      "/shoes/mocasin/21.jpg",
    ],
  },
  {
    id: 3,
    title: "Gentle Shoes",
    image: "/shoes/gentle/22.jpg",
    slug: "gentle-shoes",
    subCatId: 1,
    catId: 1,
    description: "Elegant gentle shoes for a formal look.",
    hasFreeDelivery: true,
    currentPrice: 140000,
    originalPrice: 180000,
    subCatName: "Shoes",
    images: [
      "/shoes/gentle/1.jpg",
      "/shoes/gentle/2.jpg",
      "/shoes/gentle/3.jpg",
      "/shoes/gentle/4.jpg",
      "/shoes/gentle/5.jpg",
      "/shoes/gentle/6.jpg",
      "/shoes/gentle/7.jpg",
      "/shoes/gentle/8.jpg",
      "/shoes/gentle/9.jpg",
      "/shoes/gentle/10.jpg",
      "/shoes/gentle/12.jpg",
      "/shoes/gentle/13.jpg",
      "/shoes/gentle/14.jpg",
      "/shoes/gentle/15.jpg",
      "/shoes/gentle/16.jpg",
      "/shoes/gentle/17.jpg",
      "/shoes/gentle/18.jpg",
      "/shoes/gentle/19.jpg",
      "/shoes/gentle/21.jpg",
    ],
  },
  {
    id: 4,
    title: "Boots",
    image: "/shoes/boots/11.jpg",
    slug: "boots",
    subCatId: 1,
    catId: 1,
    description: "Durable boots for outdoor adventures.",
    hasFreeDelivery: true,
    currentPrice: 160000,
    originalPrice: 200000,
    subCatName: "Shoes",
    images: [
      "/shoes/boots/1.jpg",
      "/shoes/boots/2.jpg",
      "/shoes/boots/3.jpg",
      "/shoes/boots/4.jpg",
      "/shoes/boots/5.jpg",
      "/shoes/boots/6.jpg",
      "/shoes/boots/7.jpg",
      "/shoes/boots/8.jpg",
      "/shoes/boots/9.jpg",
      "/shoes/boots/10.jpg",
      "/shoes/boots/12.jpg",
      "/shoes/boots/13.jpg",
      "/shoes/boots/14.jpg",
      "/shoes/boots/15.jpg",
      "/shoes/boots/16.jpg",
      "/shoes/boots/17.jpg",
      "/shoes/boots/18.jpg",
      "/shoes/boots/19.jpg",
      "/shoes/boots/21.jpg",
    ],
  },
  {
    id: 5,
    title: "Nike Sneakers",
    image: "/shoes/nike/4.jpg",
    slug: "nike-sneakers",
    subCatId: 1,
    catId: 1,
    description: "High-quality Nike sneakers for sports and style.",
    hasFreeDelivery: true,
    currentPrice: 99.99,
    originalPrice: 109.99,
    subCatName: "Shoes",
    images: [
      "/shoes/nike/1.jpg",
      "/shoes/nike/2.jpg",
      "/shoes/nike/3.jpg",
      "/shoes/nike/4.jpg",
      "/shoes/nike/5.jpg",
      "/shoes/nike/6.jpg",
      "/shoes/nike/7.jpg",
      "/shoes/nike/8.jpg",
      "/shoes/nike/9.jpg",
      "/shoes/nike/10.jpg",
      "/shoes/nike/12.jpg",
      "/shoes/nike/13.jpg",
      "/shoes/nike/14.jpg",
      "/shoes/nike/15.jpg",
      "/shoes/nike/16.jpg",
      "/shoes/nike/17.jpg",
      "/shoes/nike/18.jpg",
      "/shoes/nike/19.jpg",
      "/shoes/nike/21.jpg",
    ],
  },
  {
    id: 6,
    title: "Vans Sneaker",
    image: "/shoes/van/3.jpg",
    slug: "vans-sneaker",
    subCatId: 1,
    catId: 1,
    description: "Casual Vans sneakers for everyday comfort.",
    hasFreeDelivery: true,
    currentPrice: 70000,
    originalPrice: 100000,
    subCatName: "Shoes",
    images: [
      "/shoes/van/1.jpg",
      "/shoes/van/2.jpg",
      "/shoes/van/3.jpg",
      "/shoes/van/4.jpg",
      "/shoes/van/5.jpg",
      "/shoes/van/6.jpg",
      "/shoes/van/7.jpg",
      "/shoes/van/8.jpg",
      "/shoes/van/9.jpg",
      "/shoes/van/10.jpg",
      "/shoes/van/12.jpg",
      "/shoes/van/13.jpg",
      "/shoes/van/14.jpg",
      "/shoes/van/15.jpg",
      "/shoes/van/16.jpg",
      "/shoes/van/17.jpg",
      "/shoes/van/18.jpg",
      "/shoes/van/19.jpg",
      "/shoes/van/21.jpg",
    ],
  },
  {
    id: 7,
    title: "Stylish Sandals",
    image: "/shoes/sandles/24.jpg",
    slug: "stylish-sandals",
    subCatId: 1,
    catId: 1,
    description: "Fashionable sandals for a relaxed and stylish look.",
    hasFreeDelivery: true,
    currentPrice: 44.99,
    originalPrice: 49.99,
    subCatName: "Shoes",
    images: [
      "/shoes/sandles/1.jpg",
      "/shoes/sandles/2.jpg",
      "/shoes/sandles/3.jpg",
      "/shoes/sandles/4.jpg",
      "/shoes/sandles/5.jpg",
      "/shoes/sandles/6.jpg",
      "/shoes/sandles/7.jpg",
      "/shoes/sandles/8.jpg",
      "/shoes/sandles/9.jpg",
      "/shoes/sandles/10.jpg",
      "/shoes/sandles/12.jpg",
      "/shoes/sandles/13.jpg",
      "/shoes/sandles/14.jpg",
      "/shoes/sandles/15.jpg",
      "/shoes/sandles/16.jpg",
      "/shoes/sandles/17.jpg",
      "/shoes/sandles/18.jpg",
      "/shoes/sandles/19.jpg",
      "/shoes/sandles/21.jpg",
      "/shoes/sandles/22.jpg",
      "/shoes/sandles/23.jpg",
      "/shoes/sandles/24.jpg",
    ],
  },
  // PANTS
  {
    id: 8,
    title: "Mens Multi-pocket Cargo Pants Elastic Waist Hip Hop Jogging",
    image: "/pants/multi-pocket.jpg",
    slug: "generic-mens-multi-pocket-cargo-pants-elastic-waist-hip-hop-jogging",
    subCatId: 2,
    catId: 1,
    description:
      "Style:Casual Length:Full Waist Type:Elastic Waist,Low Fit Style:Fitted Pattern:Solid Decoration:Multi-pockets Season:Spring, Summer, Autumn Size: XL(cm/inch); Waist circumference:66-97/26-38.2 ; Hip circumference:106/41.7 ; Length of pants:103/40.6 colour:Dark Blue Material:Cotton Blend",
    hasFreeDelivery: true,
    currentPrice: 51452,
    originalPrice: 102904,
    subCatName: "Pants",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
  {
    id: 9,
    title: "Spring Summer Pants",
    image: "/pants/spring-summer.jpg",
    slug: "fashion-spring-summer-pants",
    subCatId: 2,
    catId: 1,
    description: "Summa Pants",
    hasFreeDelivery: true,
    currentPrice: 248000,
    originalPrice: 298000,
    subCatName: "Pants",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
  {
    id: 10,
    title: "New Men's Casual Jogging Pants Sports Pants Men's",
    image: "/pants/men-casual.jpg",
    slug: "generic-new-mens-casual-jogging-pants-sports-pants-mens",
    subCatId: 2,
    catId: 1,
    description: "Summa Pants",
    hasFreeDelivery: true,
    currentPrice: 51000,
    originalPrice: 102000,
    subCatName: "Pants",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
  //FRIDGES
  {
    id: 11,
    title: "ADH 98 Liters Double Door Refrigerator BCD 80999 - Silver",
    image: "/fridges/double-door.jpg",
    slug: "adh-98-liters-double-door-refrigerator-bcd",
    subCatId: 8,
    catId: 2,
    description:
      "Sleek and Beautiful: ADH Refrigerator is amazing! This fridge is perfect for a small office, dorm room, kitchen or playroom. The compressor cooling fridge will keep your drinks and food at a perfect temperature. With the built in freezer you can store your dinner, ice cream or other snacks!",
    hasFreeDelivery: true,
    currentPrice: 572500,
    originalPrice: 700000,
    subCatName: "Fridges",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
  {
    id: 12,
    title: "Hisense 195 Litres Single Door Silver Fridge - Silver",
    image: "/fridges/single-door.jpg",
    slug: "adh-98-liters-double-door-refrigerator-bcd",
    subCatId: 8,
    catId: 2,
    description:
      "With an optimized system design, enjoy a quieter life with low noise operation from your Hisense Refrigerator RR120DAGS. This product has a removable multiple-sealed door that can effectively isolate external heat and is also easy to clean. This product also has a multi-air flow system that distributes cold air evenly at each corner so that food quickly reaches the ideal storage temperature.",
    hasFreeDelivery: true,
    currentPrice: 802500,
    originalPrice: 1300000,
    subCatName: "Fridges",
    images: ["tshirt1.jpg", "tshirt2.jpg"],
  },
];

export { categories, subCategories, products };
