import {
  BaggageClaim,
  BarChart4,
  Bell,
  Cable,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  ExternalLink,
  FolderTree,
  Home,
  Layers2,
  LayoutGrid,
  LayoutList,
  LineChart,
  Package,
  Package2,
  Plus,
  Power,
  Presentation,
  Settings,
  ShoppingCart,
  Truck,
  User,
  Users,
  Users2,
} from "lucide-react";
export const sidebarLinks = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: Home,
    dropdown: false,
  },
  {
    title: "Banners",
    href: "/dashboard/banners",
    icon: Presentation,
    dropdown: false,
  },
  {
    title: "Products",
    icon: LayoutGrid,
    href: "/dashboard/products",
    dropdown: false,
  },
  {
    title: "Categories",
    icon: Layers2,
    href: "/dashboard/categories",
    dropdown: false,
  },
  {
    title: "Sub Categories",
    icon: LayoutList,
    href: "/dashboard/sub-categories",
    dropdown: false,
  },
  {
    title: "Users",
    icon: Users,
    href: "/dashboard/users",
    dropdown: false,
  },
  {
    title: "Customers",
    icon: Users2,
    href: "/dashboard/customers",
    dropdown: false,
  },
  {
    title: "Orders",
    icon: Truck,
    href: "/dashboard/orders",
    dropdown: false,
  },
  {
    title: "Profile",
    icon: User,
    href: "/dashboard/profile",
    dropdown: false,
  },
  {
    title: "Online Store",
    icon: ExternalLink,
    href: "/",
    dropdown: false,
  },
  {
    title: "Settings",
    href: "/dashboard/settings",
    icon: Settings,
    dropdown: false,
  },
];
